name: blood_donation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: any
  flutter_svg: any
  shared_preferences: any
  firebase_core: any
  cloud_firestore: any
  flutter_phone_direct_caller: any
  firebase_auth: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  http: ^1.2.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  flutter_phone_direct_caller: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/avtar/
