// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jN1IzS5pK31_200EW0L0Le4tqpGeznM',
    appId: '1:283486625334:web:5e59d1ae757fd5737b4297',
    messagingSenderId: '283486625334',
    projectId: 'blooddonation-9aca9',
    authDomain: 'blooddonation-9aca9.firebaseapp.com',
    databaseURL: 'https://blooddonation-9aca9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blooddonation-9aca9.appspot.com',
    measurementId: 'G-X7KDCHNM1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuZlpTGQTJE9euTeMPujBDbOr0w_5Iox0',
    appId: '1:283486625334:android:21c505a6700053dd7b4297',
    messagingSenderId: '283486625334',
    projectId: 'blooddonation-9aca9',
    databaseURL: 'https://blooddonation-9aca9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blooddonation-9aca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA65jkY9xAXizZGCR3A-zxHnK3EgqCXolE',
    appId: '1:283486625334:ios:887c9bd5dafa030d7b4297',
    messagingSenderId: '283486625334',
    projectId: 'blooddonation-9aca9',
    databaseURL: 'https://blooddonation-9aca9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blooddonation-9aca9.appspot.com',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA65jkY9xAXizZGCR3A-zxHnK3EgqCXolE',
    appId: '1:283486625334:ios:887c9bd5dafa030d7b4297',
    messagingSenderId: '283486625334',
    projectId: 'blooddonation-9aca9',
    databaseURL: 'https://blooddonation-9aca9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blooddonation-9aca9.appspot.com',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7jN1IzS5pK31_200EW0L0Le4tqpGeznM',
    appId: '1:283486625334:web:7d45ffd32df343237b4297',
    messagingSenderId: '283486625334',
    projectId: 'blooddonation-9aca9',
    authDomain: 'blooddonation-9aca9.firebaseapp.com',
    databaseURL: 'https://blooddonation-9aca9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blooddonation-9aca9.appspot.com',
    measurementId: 'G-XZEPDL0KCS',
  );
}
